### ISSUE TITLE
rabbitmq topic mismatch

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-gkeeper#308]
@jbonnet The topic defined in the SLM is service.instance.create https://github.com/sonata-nfv/son-mano-framework/blob/master/plugins/son-mano-service-lifecycle-management/son_mano_slm/slm.py#L51

Do you should use the same topic here? 
https://github.com/sonata-nfv/son-gkeeper/blob/master/son-gtksrv/models/mq_server.rb#L37

**Comment by jbonnet** [comment]
Closed by #309
