### ISSUE TITLE
User management design

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#332]
Finalize design of all features planned for 2016
Tools, workflow for user management component (including 'user' and 'microservice' elements)
[son-gtkusr discussion link](http://wiki.sonata-nfv.eu/index.php/User_Mgmt_Discussion)

**Comment by jbonnet** [comment]
@shuaibsiddiqui @dang03 What's the status of this?

**Comment by dang03** [comment]
Hi @jbonnet, I updated the wiki page [User Management design link](http://wiki.sonata-nfv.eu/index.php/User_Mgmt_Discussion#User_Management_pre-Final_design) with some more details about the design with the support of some testings I have been doing.
While this is not final yet, @shuaibsiddiqui and me will be meeting next Friday (he is currently out) to take final steps on design.

**Comment by jbonnet** [comment]
Ok, @dang03 , great! ;-)
Pity we won't be able to discuss this this thursday...

**Comment by jbonnet** [comment]
@dang03 @shuaibsiddiqui I think it would be clearer if at least a minimum set of User Stories could be written about how each one of the roles/modules could use the User Management modules, what do you think?

**Comment by dang03** [comment]
Design phase was closed.
User Management module initial version released, integrated release for Release v3.0
Current phase of enhancements, new features implementation.
