### ISSUE TITLE
Sign packages

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#342]

**Comment by jbonnet** [comment]
Hello, @dang03 
Can you point me or write here what's is needed to sign packages?
Thanks,

**Comment by dang03** [comment]
Hello @jbonnet,
When a signed package is submitted to the GK API, the extra data it will include is the signature hash.
It will be included as a header:
`headers['signature'] = signature`
So the GK API will receive:
Headers: 
```
{'Authorization': "Bearer %s" % access_token}
{'signature': signature}
```

Body:
`{'package': pkg_file}`

**Comment by jbonnet** [comment]
Ok, @dang03, great!
Is `son-access` already sending this header?

**Comment by dang03** [comment]
@jbonnet 
Yes, it is already implemented. Remember that signing is an optional argument in the `son-access`, the GK API won't always receive the signature.

**Comment by jbonnet** [comment]
@dang03 
And what's the signing algorithm to be applied on the GK's side?

**Comment by dang03** [comment]
@jbonnet 
In the GK side, it should be applied the Signature Verification, however, as mentioned in Paris F2F, this functionality will be inside the son-validate, which will be called by the GK.
The GK should get the received `signature`, the User's `public key` from the UM, and the `hash value of the original package file` OR the `package file` itself, and send them to the validation function.

How the Verification works:
The receiving side calculates the `hash value `of the package file (binaries) and then uses the User's `public key` with the verify() method to validate its origin:

Using Python (son-validate) Crypto lib
```
from Crypto.Hash import SHA256 
from Crypto.PublicKey import RSA

def verify(son-package, public_key, signature):
  hash = SHA256.new(son-package).digest()
  result = public_key.verify(hash, signature)
```
It returns `True` or `False`

**Comment by jbonnet** [comment]
Closed, signing is done by `son-validate`
