### ISSUE TITLE
Change user id from header to url param

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#358]
When we want to list licences belonging to a certain user, we're using a header with the User UUID. We need to use the user ID in the URL instead, like in
`
.../licences?user_id=:user_id
`
Thanks

**Comment by bsilvr** [comment]
The code was as you requested the problem was with the documentation, it's fixed now plus other minor fixes in the documentation. Should we do another pull request?

**Comment by jbonnet** [comment]
:-)
Yes please.

**Comment by jbonnet** [comment]
Closed by #418
