### ISSUE TITLE
son-gtkapi broken?

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#375]
son-gtkapi is no working properly for some interfaces. Next list show interfaces tested that resulted in failure:
http://sp.int3.sonata-nfv.eu:32001/services
- when listing available services in catalogue (404 not found) when nsds present in the catalogue
For /functions and /packages, it works correctly

http://sp.int3.sonata-nfv.eu:32001/services/uuid
- when getting ansd by its uuid (404 not found) when the nsd is present in the catalogue

http://sp.int3.sonata-nfv.eu:32001/functions/uuid
- when getting a vnfd by its uuid (500 error)

**Comment by jbonnet** [comment]
Please check again, @dang03 , PR#373 is supposed to have solved several issues

**Comment by dang03** [comment]
Thank you @jbonnet. Most of the issues have been solved. However, there's a interface that still broken:
http://sp.int3.sonata-nfv.eu:32001/api/v2/functions/uuid

It does not show any error code, CLI returns this error:
'Connection broken: IncompleteRead(36 bytes read)', IncompleteRead(36 bytes read)
Even POSTMAN fails to get any response, it shows 'Could not get any response'.

From Catalogue side it is working properly.

**Comment by jbonnet** [comment]
Very strange… let me look at it. I’ve noticed you’re using INT3 env; is this behaviour the same when INT env is used?

José Bonnet
jose.bonnet@me.com

**Comment by dang03** [comment]
Ok, for INT env it is working properly.
I'm trying to find where's the MongoDB that INT env is using, as the one we are working on is in INT3 env.

**Comment by jbonnet** [comment]
:-)
Just let me know if the problem still stands.

José Bonnet
jose.bonnet@me.com

**Comment by dang03** [comment]
Yes, the problem persists even in INT env when the GK finds the function descriptor queried by UUID.
It works fine when you ask for function descriptor that is not found (returns 404 properly).

E.g.:
sudo curl --request GET --url http://sp.int.sonata-nfv.eu:32001/api/v2/functions/dce3cffd-4957-40fe-adcc-cdc41c97a805 --header 'content-type: application/json'
curl: (56) Problem (2) in the Chunked-Encoded data

**Comment by jbonnet** [comment]
Ok, I’ll take a look,
José Bonnet
jose.bonnet@me.com

**Comment by jbonnet** [comment]
@dang03 This is really strange. This 'Transfer-Encoding: chunked' is supposed to happen when streaming, which we're not doing. Are you sure you're not somehow setting this HTTP header from within the Catalogues?

**Comment by dang03** [comment]
I've been checking the Catalogue and there's no sign of a different header except for x-yaml and json. I've tested it for this particular case with CLI curl and postman and works fine.

From GtkAPI logs, I can see that it resolves the query succesfuly, the descriptor arrives fine to the GK:
INFO -- GtkFnct GET /functions/:uuid: leaving with response={"author":"Steven ".................}

But the response doesn't reach the destination. It also has been tested with 'son-tests' integration tests remotely, so I don't know what it can be.

**Comment by jbonnet** [comment]
@dang03 Please repeat your tests: I think it is fixed with pr/#376

**Comment by dang03** [comment]
The issue is solved now. Integration tests in INT and INT3 envs now work properly. We can close the issue.
Thanks.

**Comment by jbonnet** [comment]
Closed by pr/#376
