### ISSUE TITLE
Return only JSON from Lic. Manager module

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#382]
I’m getting redirected when POSTing a new type, with this response:

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://localhost:5000/api/v1/types/">http://localhost:5000/api/v1/types/</a>.  If not click the link.
```

The API should always get JSON, not HTML…

**Comment by bsilvr** [comment]
could you provide any additional info regarding the problem? i'm not able to recreate the issue

**Comment by jbonnet** [comment]
Sure, @bsilvr: if you do a `curl localhost:5900/api/v1/types` (`localhost:5900` being the lic. manager micro-service) in the command line, you'll get the `HTML` I've written above.

Redirection is probably something else, I'm still looking at it: it might be related with failure to access the PostgreSQL database (which is in another container).

**Comment by jbonnet** [comment]
Hello,
Any new on this? Were you able to replicate the issue?

**Comment by jbonnet** [comment]
Forget it: redirection is caused by not writing a trail `/` ([see here](https://github.com/flask-restful/flask-restful/issues/65), i.e.,
* redirects: `$ curl -v sp.int3.sonata-nfv.eu:5900/api/v1/types`
* does not redirect: `$ curl -v sp.int3.sonata-nfv.eu:5900/api/v1/types/`

Code could be improved by making the trailing `/` optional, but that's not very important
