### ISSUE TITLE
URL upload package in integration

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-gkeeper#384]
Upload a package to integration is failing. I guess the reason is bad url. What is the new url to upload a package?

This is the log
curl -i -X POST -F package=@sonata-fw-vtc-service-sp.son http://sp.int3.sonata-nfv.eu:32001/packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  6999    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  7017  100    18  100  6999     17   6675  0:00:01  0:00:01 --:--:--  6678
HTTP/1.1 100 Continue

HTTP/1.1 404 Not Found
Content-Type: text/html;charset=utf-8
X-Cascade: pass
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Length: 18

<h1>Not Found</h1>

**Comment by dang03** [comment]
The new url should be this:  http://sp.int3.sonata-nfv.eu:32001/api/v2/packages
