### ISSUE TITLE
Fix int-gtkpkg-sp-catalogue tests5

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#412]
This integration test started failing since yesterday

**Comment by jbonnet** [comment]
The failure is due to a new field, `son_package_uuid`, which started appearing in the package meta-data and 'puzzled' the integration test logic (which looks for a `uuid` field and catches them both).

@dang03: we need to improve this, even though @felipevicens will improve the test. I guess this new field is part of the 'Get package file' feature. If it is, we need to evolve into that data/meta-data split we've been talking about for some time. Just let me know when you have some time, and we can talk about this.

**Comment by dang03** [comment]
Hi @jbonnet, I already did a fix for this bug and some improvement to the test, however is not pushed yet.
Yes, it is related with the 'Get package file' feature. As this feature is not yet ready, I've considered it in the integration tests.

**Comment by dang03** [comment]
Tests5 is now fixed. Descriptor uuid and file uuid are now handled properly. The file uuid will be used for test when Gatekeeper is able to retrieve a package file through /son-packages/:uuid API. I know it was implemented but is not ready yet.
