### ISSUE TITLE
Fix missing folder

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#423]

**Comment by jbonnet** [comment]
Hey, @Bernardomrf, @bsilvr 
Integration tests are failing due to the missing `code/log/production.log` folders and file. Can you please check this out and create the folder if it doesn't exist? 

Thanks

**Comment by jbonnet** [comment]
test this please

**Comment by bsilvr** [comment]
Folder was in the gitignore file, it's fixed in the new pull request. Only logs are ignored now not the folder

**Comment by jbonnet** [comment]
Closed by #424
