### ISSUE TITLE
Improve KPIs' README

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#437]
Hi, @srodriguezOPT 

Could you please improve the KPIs module README with more examples? The creation of a KPI is already there, but not the usage of existing KPIs. This will be crucial for @trakadasp and @mzacharioudakis  in the GUI...

**Comment by srodriguezOPT** [comment]
Hi,

The KPI module README has been updated. 
The son-gtkapi/views/api_doc.erb was updated too.

**Comment by jbonnet** [comment]
Top, Santi!

Thanks
