### ISSUE TITLE
Update Licensing API

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#441]

**Comment by jbonnet** [comment]
You can already list (`GET .../licences`), see (`GET .../licences/:licence_uuid`) and create (`POST .../licences`) licences. Update and delete is next.

**Comment by srodriguezOPT** [comment]
GET http://sp.int3.sonata-nfv.eu:32001/api/v2/licences/

returns
{
  "error": {
    "code": 404,
    "message": "No licences with {\"offset\"=>\"0\", \"limit\"=>\"10\"} were found"
  }
}

**Comment by jbonnet** [comment]
@srodriguezOPT 
Hi, Santi,
Couldn't reproduce this:
`$ curl sp.int3.sonata-nfv.eu:32001/api/v2/licences/
[]`
An empty array is what's expected, right? Would you mind repeating the test, please?

**Comment by srodriguezOPT** [comment]
Hi @jbonnet ,

You are right. Now it's returning an [ ] that is what we expect if there are no licences
