### ISSUE TITLE
Start registering KPIs

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#447]
Now that we have the KPIs module, we need to start registering data.

**Comment by jbonnet** [comment]
Hey, @srodriguezOPT 
I've been reading the [examples](https://github.com/sonata-nfv/son-gkeeper/tree/master/son-gtkkpi#implemented-api), and I have some doubts. For example, I want to register the number of packages submitted, some will be ok, others will be rejected because of an error or lack of permission, others will be duplicate, etc.
1. What should I send in `job` and `instance` fields?
1. What are the `base_labels` you mention, are they like `{'created_at':'...', 'user_uuid':'...', ...}`?

Thanks

**Comment by srodriguezOPT** [comment]
Hi @jbonnet ,

Let me show you an example of how prometheus will store the counter/gauge:

gk_maxApiCalls(exported_instance="gatekeeper", exported_job="api calls",..., "base_labels": {"api name": "services", "method": "GET"})
gk_maxApiCalls(exported_instance="gatekeeper", exported_job="api calls",..., "base_labels": {"api name": "services", "method": "POST"})
gk_maxApiCalls(exported_instance="gatekeeper", exported_job="api calls",..., "base_labels": {"api name": "services", "method": "PUT"})
gk_maxApiCalls(exported_instance="gatekeeper", exported_job="api calls",..., "base_labels": {"api name": "functions", "method": "GET"})

So, we can use instance and job to identify the origin and type of the KPI. 
Another example of an existing vim KPI: vim_maxServerGroupMembers{exported_instance="POP_2",exported_job="limits"...

With the base_labels, prometheus will create a counter/gauge with every set of base_labels. In the example:
a gk_maxApiCalls gauge/counter with the api GET /services count
a gk_maxApiCalls gauge/counter with the api POST /services count
....

We can use the base labels for the service status, the http error code, etc.

**Comment by jbonnet** [comment]
@srodriguezOPT 
Can you please add some KPIs registration code.. to the KPIs service?
That would be nice playing as examples...

Thanks,

**Comment by srodriguezOPT** [comment]
Hi @jbonnet ,

In http://sp.int3.sonata-nfv.eu:9091/ you can check the counter/gauges created in the pushgateway. 

For example, the job="sonata", instance="gtkkpi" both examples (example_gauge and example_counter) were created with the https://github.com/sonata-nfv/son-tests/tree/master/int-gtkkpi-prometheus tests; In test1.sh and test2.sh, you can check that the REST invocations are like

curl -H 'Content-Type: application/json' -X PUT -d '{ "metric_type": "counter", "job": "sonata", "instance": "gtkkpi", "name": "example_counter", "docstring": "metric counter test", "base_labels": {"label1": "value1", "label2": "value2"}}' http://sp.int3.sonata-nfv.eu:32001/api/v2/kpis)

**Comment by jbonnet** [comment]
Super!
Thanks, consider it done!
:-)

**Comment by jbonnet** [comment]
Closed by #461
