### ISSUE TITLE
User Management - Monitoring

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#489]
1. Create `role` for Monitoring POP Administrator
2. Set access to monitoring resource only for developers `role`
3. Update `mapping` for Monitoring
4. Implement authorization process for monitoring requests where:
- Catalogue needs to store meta-data of developer `username`
- Check Catalogue contents authored by developer `username`
- Check running instances that allows to access monitoring data to developer `username`

**Comment by jbonnet** [comment]
Hey, @dang03 
Can you please elaborate a bit on this issue? Where do you think this could be used?

**Comment by dang03** [comment]
Hi @jbonnet 
This was the outcome of the Monitoring dedicated call we had.
In order to authorize a developer to request monitoring data, these points must be met.
GK API should have to send `username` to the Catalogues of the `POST`ing developer when storing a package.

**Comment by jbonnet** [comment]
Ok, but we have to talk about the implementation. I was thinking of a simple validation of the service/function owner (yes, descriptors in the Catalogue have to have this). But then what authorisation is there to implement?

**Comment by dang03** [comment]
@jbonnet, @shuaibsiddiqui 
The authorization to be implemented is not fully defined, there's one missing point. What we expect is:
- A developer requests monitoring data of a service instance to the GK API
- Counting that descriptors meta-data include `username` of the owner then...
- GK API asks UM, it gets all descriptors belonging to `username` and checks running instances for any of these descriptors and the requested instance. It should check if the instance authorizes the developer...
- but the MISSING point is: how can a `customer` authorize a `developer` to monitor an instanced service?

Can you give more details about the validation you thought of the service/function owner?
Who is the owner? `vendor`, `username` (developer), ...? 
Catalogues store `vendor` and `maintainer`, but no `username` yet.

**Comment by jbonnet** [comment]
Hey, @dang03, @shuaibsiddiqui 
* First two bullets above are ok
* It is the GK that gets the specified service/function for the Catalogue
* The GK validates that the requesting developer is the owner of the service/function
    * we may argue here that monitoring data on public services/function may be requested by anyone, while monitoring data on private services/functions can only be seen either their owners or developers that bought a licence to (re-)use that service/function
* The GK passes the Monitoring manager the information passed by the developer, and the web socket is established

As you see, there's no UM involved here. What am I missing?

**Comment by dang03** [comment]
Hi @jbonnet 
As you state in your workflow, UM is not needed then. It is fine then, however we have some doubts:

1. How GK validates the owner of the service/function? Does it check the repositories? Is the developer ID (`username`) included in the repositories?
2. What are the differences between public and private service/functions?
3. Customer is the owner of the instantiation of a service. Instead, do we assume that the developer is the owner and not the customer? Or has the developer access to the running instances? Elaborating more on this question, customer is involved in monitoring request: A customer instantiates a service (he might paid for it) but he doesn't want anybody to monitor his data. Is this considered?

**Comment by jbonnet** [comment]
@dang03 
Of course we can make this flow more complete, but that's not the point.
1. Service/function descriptors must have user `UUID` in their meta-data, therefore the need for  the user registration process to return that (it could be the `username`, but we've been working with `UUID` all over, we should be consistent) and the need for a `GET .../users/:uuid` API;
1. By default a service or function is public. If private, its developer has to state that in the schema and provide a URL for a 'licence store', where other developers can buy 're-use' licence and customers can buy 'instantiation' licences (this has been discussed in the Porto meeting);
1. The purpose of monitoring a service/function instance is for improvement only. Therefore I've been insisting that this monitoring should not go on until the developer closes the websocket. Of course we're simplifying here: in the real world, the GK would have to guarantee that certain fields would not be monitored. In the real world, the web page where the customer buys the service would have a small check box saying that the platform owner/service developer reserve the right to temporarily monitor the service for performance reasons.

**Comment by dang03** [comment]
This feature is implemented by GTK API
