### ISSUE TITLE
Validate packages using the SDK's validator service

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#532]
The SDK has a package validator that is exposing as a service. The API should connect to it to validate packages on the SP side. **Note:** this shouldn't be a repetition of the validations done at the SDK side.

**Comment by jbonnet** [comment]
API is documented in [here](https://github.com/sonata-nfv/son-cli/blob/master/src/son/validate/README.md)

**Comment by jbonnet** [comment]
Check the **API** [here](https://github.com/sonata-nfv/son-cli/tree/master/src/son/validate#api)

**Comment by jbonnet** [comment]
Hey, @lconceicao,
Going through the [`son-validate` API documentation](https://github.com/sonata-nfv/son-cli/blob/master/src/son/validate/README.md#api), some doubts came to my mind:
1. shall the GK pass a package, a service and a function separately? Or can it pass the entire `.son` file?
1. Is this an asynchronous API?

Thanks

**Comment by lconceicao** [comment]
Hello @jbonnet ,

1. It can pass the entire package. For this you can use the `/validate/package` endpoint. Also, the package itself can be embedded in the request body or a URL can be provided indicating the package location.
For the first case (embedded) the body in the request would look something like this:
source: "embedded"
file: (the file itself)
For the second case (URL) it would look like:
source: "url"
path: (the URL for the package file)

2. Do you mean if waits for the response? Yes, the API will block until the response is retrieved. It is possible to implement this asynchronously, however the GK would have to perform at least 2 requests.

**Comment by jbonnet** [comment]
Great, @lconceicao 
1. Ok;
2. No, I just saw the `/reports` endpoint and got that doubt...

**Comment by lconceicao** [comment]
@jbonnet,
For the latest version of the API documentation please refer to: `https://github.com/lconceicao/son-cli/tree/son-validate-events/src/son/validate`

I will merge this soon, but the jenkins tests are taking forever...

**Comment by jbonnet** [comment]
Ok, I'm on it...
By the way, what HTTP codes should be expected on the GK's side? `200` (Ok), and...?

**Comment by lconceicao** [comment]
Well, for the moment the API is returning 200 when it is able to perform the validation (independently of the validation result) and a 400 when it doesn't have all the required components/parameters to do a validation, associated with an error message.
