### ISSUE TITLE
Implement login/logout GK API

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#587]
The feature is ready on the UM side, it's just not yet connected with the GK API.

**Comment by jbonnet** [comment]
@srodriguezOPT, @mzacharioudakis 
The logout API seems to be ready (PR #590):
`DELETE .../api/v2/sessions`, with `AUTHORIZATION` header set to `Bearer <token>`.

Let me know if this is it.

**Comment by srodriguezOPT** [comment]
@jbonnet 
"XMLHttpRequest cannot load https://sp.int3.sonata-nfv.eu/api/v2/sessions. Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response."

**Comment by jbonnet** [comment]
Ha!
It’s that options block…
Fixing

**Comment by jbonnet** [comment]
@srodriguezOPT 
PR #594 fixed that, please re-test.

**Comment by srodriguezOPT** [comment]
@jbonnet 
"XMLHttpRequest cannot load https://sp.int3.sonata-nfv.eu/api/v2/sessions. Method DELETE is not allowed by Access-Control-Allow-Methods in preflight response." again

**Comment by jbonnet** [comment]
@srodriguezOPT How come? :-(
Please check [here](https://github.com/sonata-nfv/son-gkeeper/blob/master/son-gtkapi/routes/sessions_controller.rb#L39)

**Comment by srodriguezOPT** [comment]
@jbonnet , a namespace issue?

Compare:

namespace '/api/v2' do
    before do
      if request.request_method == 'OPTIONS'
        response.headers['Access-Control-Allow-Origin'] = '*'
        response.headers['Access-Control-Allow-Methods'] = 'POST,DELETE'      
        response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With'
        halt 200
      end
    end

against

    namespace '/api/v2/services' do
    #options '/' do
    before do
      if request.request_method == 'OPTIONS'
        response.headers['Access-Control-Allow-Origin'] = '*'
        response.headers['Access-Control-Allow-Methods'] = 'POST,PUT'      
        response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With'
        halt 200
      end
    end

and
	
    namespace '/api/v2/vims' do
      before do
        if request.request_method == 'OPTIONS'
          response.headers['Access-Control-Allow-Origin'] = '*'
          response.headers['Access-Control-Allow-Methods'] = 'POST'
          response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With'
          halt 200
        end
      end

**Comment by jbonnet** [comment]
Right, Mr. Hawk-eye... ;-)
Fixing

**Comment by jbonnet** [comment]
PR #596 fixes this.
Can you try again, @srodriguezOPT, please?

**Comment by srodriguezOPT** [comment]
Same result:

![image](https://cloud.githubusercontent.com/assets/15909508/25667248/36dfba0c-3023-11e7-9dc5-4b3b6d08aa67.png)

OPTIONS call ok, but the DELETE one fails...

**Comment by srodriguezOPT** [comment]
@jbonnet wait, look at the picture!
in OPTIONS,
request headers: method DELETE
but response headers: methods POST and PUT, not DELETE

**Comment by jbonnet** [comment]
Ok,
I have to investigate further.
It seems that the problem is in the answer… have you tried using curl? My tests worked with
`curl -X DELETE -H 'Authorization:bearer eyJhb...PR5hLw' localhost:5000/api/v2/sessions`

where the `eyJhb…PR5hLw` is the token you get when you log a user in.

**Comment by srodriguezOPT** [comment]
@jbonnet ,
curl command doesn't show me the response's headers but if you try with a REST client like Postman, the response is

![image](https://cloud.githubusercontent.com/assets/15909508/25693403/5d8103d8-30a9-11e7-9d31-8d245aa6ec61.png)

I was looking for other namespaces and users_controller is the only one that

**Comment by jbonnet** [comment]
I’ll implement this with PUT (instead of DELETE), let’s see if it works

**Comment by srodriguezOPT** [comment]
Or you can try to include "licences" in the namespace of son-gtkapi/routes/licence.rb:

namespace '/api/v2/licenses' do
#options '/' do
before do
if request.request_method == 'OPTIONS'
response.headers['Access-Control-Allow-Origin'] = '*'
response.headers['Access-Control-Allow-Methods'] = 'POST,PUT'
[...]

**Comment by felipevicens** [comment]
@jbonnet it is working from my side

**Comment by srodriguezOPT** [comment]
@jbonnet 

- the "allow method" issue is solved
- instantiation requests and get services/instances are working

DELETE still failing but now the response is:
{"error":{"code":400,"message":"Unprocessable entity: authorization header must be \"Bearer <token>\""}}
even when the Bearer token is provided (in the same way that in the instantiation and get requests)

**Comment by jbonnet** [comment]
Ok, @felipevicens, that's great.
@srodriguezOPT: great as well; now that's another problem: the error message might be misleading, what token are you sending back?

**Comment by srodriguezOPT** [comment]
@jbonnet ,
with the response.data.token from login response bss creates the
$http.defaults.headers.common.Authorization = 'Bearer ' + response.data.token;

the problem is that response.data.toke is an object like 
{
  "username": "test",
  "session_began_at": "2017-05-04 10:31:27 UTC",
  "token": {
    "access_token": "eyJhbGciOiJSUzI1NiIsIn...",
    "expires_in": 300,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia...",
    "token_type": "bearer",
    "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuZWh1d2pvY...",
    "not-before-policy": 0,
    "session_state": "4049b113-67f2-4ff1-b5ed-4156ce0b839e"
  }
}

which is the right one? access_token, refresh_token or id_token?
I can change the bss code to get the response.data.token.access_token

but

why does it work for the other GK's invocations? I thinked that the validation was the same

**Comment by jbonnet** [comment]
Please use the `access_token` (`eyJhbGciOiJSUzI1NiIsIn...`).

> why does it work for the other GK's invocations? I thinked that the validation was the same
Which ones? The GK is not yet validating the token in any request: we need first to have this user registration/login/logout done.

**Comment by dang03** [comment]
hi @srodriguezOPT,
The token provided by the UM is the complete JWT. Then, in order to login/logout, etc.. you neet to parse it and get the `access_token` contents.

**Comment by srodriguezOPT** [comment]
deploying....

@dang03 yes, i'm totally agree but... the token is needed to get available services and make instantiation requests, right? These operations are working even with a "wrong" token

**Comment by jbonnet** [comment]
@srodriguezOPT 
In those situations (get available services and make instantiation requests) the token is not being validated yet.

**Comment by srodriguezOPT** [comment]
@jbonnet 
logout done:

![image](https://cloud.githubusercontent.com/assets/15909508/25701486/ecb3fe20-30cc-11e7-9df8-13cfb1303c34.png)

**Comment by jbonnet** [comment]
Perfect, @srodriguezOPT 👍
