### ISSUE TITLE
Authenticate user on function description query

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#602]

**Comment by jbonnet** [comment]
hey, @dang03 
Authorization for GETting services (`{path: '/services', method: 'GET'}`) and functions (`{path: '/functions', method: 'GET'}`) is failing... is it ready on the UM? Also, do you distinguish when we do `.../services/` and `.../services/:uuid`?

**Comment by dang03** [comment]
Hi @jbonnet 
I've tested both and they return `200 OK`, here are some details:
- Services: 
URL= `POST sp.int3.sonata-nfv.eu:5600/api/v1/authorize`
HEADERS= `Content-type: application/json`
`Authorization: 'Bearer eyjj........'`
BODY= `{"path": "/services", "method": "GET"}`

- Functions:
URL= `POST sp.int3.sonata-nfv.eu:5600/api/v1/authorize`
HEADERS= `Content-type: application/json`
`Authorization: 'Bearer eyjj........'`
BODY= `{"path": "/functions",  "method": "GET"}`

In cases such `.../functions/:uuid`, the UM will not consider the `:uuid` yet, and it will ignore it.
Right now we don't have that level of permission granularity, but keep it in the GK as the new authorization mechanism will consider it soon.

**Comment by jbonnet** [comment]
Closed by PR #674
