### ISSUE TITLE
Add public key update API

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#605]
The UM is expecting a `PUT /api/v1/signatures/:username` with a body like `{"public_key":"..."}`.
HTTP method: PUT
Authentication header includes the user's Access Token
Parameter: username
Body: JSON object that includes public_key field (required) and certificate field (optional). Sample:
{"public_key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVFiBHBiLPFRGrMobAxcK98SJRKKXJOkA66NL0UEgR7g8hOjVySchYUvtGAU5wi2ZCjmPGDT0hrJd1WEBplv0kT7YrIgdRGXGH73OJFjH8c7iX+XBwk0sH1K+KMUbszSbWFCKAlyHhYa8vz95RyzmzoMJZW6TeadlhRLuVw52RECaK9eIJu311oFA8os3z8J65olLexT0vF+B9Oqtn1gVJUfC0w984PXwMoGzSOVCbb5jD0/blAXonMS8PU+JFSGF4trTwRcmjw349NDEifUQamdHE8pynuxSpAuMN2WAPAlJpjnw/fHUxQFgRNGki6vHmegnQ6qmcbuorVW3oXkMwIDAQAB", "certificate": "optional"}

**Comment by jbonnet** [comment]
hello, @dang03 
What (HTTP) return codes can we expect from the UM with this call (`PUT /api/v1/signatures/:username`)?

**Comment by dang03** [comment]
Hi @jbonnet 
The `signatures` API returns the next codes:
- `200` when signature is successfully updated
- `400` for next cases: 

       - Provided username does not match with Access Token
       - No username specified
       - Developer public key not provided

- `401` when Token is not valid
- `404` when Username is not found
- `415` when Content-type is not valid (application/json)

**Comment by jbonnet** [comment]
Closed by PR #672 
@dang03 which system is the client for this API, `son-access`? Can you please try?

**Comment by dang03** [comment]
@jbonnet 
Yes, it is the SDK `son-access` the client that will update user public key.
Im going to test it.

**Comment by dang03** [comment]
@jbonnet 
Gatekeeper API returns 500 error when updating user's Public Key:
`ERROR -- : {"error":{"code":500,"message":"#<ArgumentError: wrong number of arguments (1 for 0)>"}}`

**Comment by jbonnet** [comment]
Ok,
Can you please give more details?
Which user was used?

**Comment by jbonnet** [comment]
Hey, @dang03 
Can you test again, please? PR #674 solves some issues found... hope they were all found!
Thanks

**Comment by dang03** [comment]
Hi @jbonnet,
It is still failing. The User's Public Key is not updated in the database as it seems the UM receives the `PUT` request with the `public_key` as `null`.
The response received in the `son-access` also fails as it breaks 'requests' lib with the next exception:
`ValueError: invalid literal for int() with base 16: b'HTTP/1.1 500 Internal Server Error\r\n'`

Here are the UM logs:
```
...
DEBUG -- : Adapter: entered PUT /signatures/user04
...
"PUT /api/v1/signatures/user04 HTTP/1.1" 200 - 0.0219
...
```
Here are the GK API logs:
```
...
D, [2017-05-30T13:05:51.700093 #6] DEBUG -- GtkApi::User#save_public_key: entered
D, [2017-05-30T13:05:51.700152 #6] DEBUG -- GtkApi::ManagerService#putCurb: entered with url=http://son-gtkusr:5600/api/v1/signatures/user04, body={"public_key":null,"certificate":null}
D, [2017-05-30T13:05:51.700213 #6] DEBUG -- GtkApi::ManagerService#putCurb: header[Content-type]: application/json
D, [2017-05-30T13:05:51.700244 #6] DEBUG -- GtkApi::ManagerService#putCurb: header[Accept]: application/json
...
```

**Comment by jbonnet** [comment]
Ok, @dang03 
That's bug documentation! ;-)
Opened this #675
