### ISSUE TITLE
Fix metrics collections

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#612]
curl https://sp.int3.sonata-nfv.eu/api/v2/kpis?name=user_registrations&start=2017-05-05T14:13:02.699Z&end=2017-05-05T14:33:02.699Z&step=10m
I get as response:
{
"error": {
"code": 400,
"message": "No list of KPIs was returned"
}
}

But, if I make the same request directly to Mon-Manager:
curl -H "Content-Type: application/json" -d '{"name":"user_registrations","start":"2017-05-05T14:13:02.699Z","end":"2017-05-05T14:33:02.699Z","step":"10m","labels":[{}]}' http://sp.int3.sonata-nfv.eu:8000/api/v1/prometheus/metrics/data

I receive data:
{
"metrics": {
"resultType": "matrix",
"result": [{
"metric": {
"exported_instance": "gtkapi",
"group": "development",
"exported_job": "sonata",
"module": "users",
"elapsed_time": "0.593299396",
"instance": "pushgateway:9091",
"job": "sonata",
"result": "ok",
"name": "user_registrations",
"method": "POST",
"uuid": "b70863c9-9b92-4733-b45a-1990362bb2ef"
},
"values": [
[1493994782.699, "1"]
]
}]
}
}

**Comment by jbonnet** [comment]
@pkarkazis I can see that you're using `PORT 8000` of the PushGateway, but the KPIs service in the GateKeeper has it as `9091`...
@srodriguezOPT can you please confirm that this is the right port to address these requests?

**Comment by srodriguezOPT** [comment]
@jbonnet yes, 9091 is the pushgateway default port.

You can see it running in http://sp.int3.sonata-nfv.eu:9091/

**Comment by pkarkazis** [comment]
@jbonnet pushgateway is running on port 9001, but the kpis must be retrieved from monitoring manager (which is running on port 8000)

**Comment by jbonnet** [comment]
Ok, @pkarkazis, @srodriguezOPT 
My mistake: I was simply considering just the pushgateway for both features, which is wrong.
Fixing...

**Comment by jbonnet** [comment]
Hi, @pkarkazis 
I've refactored the code, and when I use
`curl 'localhost:5000/api/v2/kpis?name=user_registrations&start=2017-05-05T14:13:02.699Z&end=2017-05-05T14:33:02.699Z&step=10m'`
I'm getting
`{:metrics=>{:resultType=>"matrix", :result=>[]}}`.
Is this what's expected?

**Comment by jbonnet** [comment]
Closed by PR #617

**Comment by pkarkazis** [comment]
You get an empty table. it means that there is no values for the requested time window/step.

**Comment by jbonnet** [comment]
Ok,
I've closed the issue because I think I've solved it. We need to test it.

**Comment by pkarkazis** [comment]
Ok, I agree.
