### ISSUE TITLE
Add missing fields to the GK API to support package signing validation

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#618]
Packages are being signed with its developer's private key, which have to be verified using the public key stored by the same developer when registered.

This validation will be done in sonata-nfv/son-validate, to which the GK has to pass the developer's public key.

**Comment by jbonnet** [comment]
Check the [API](https://github.com/sonata-nfv/son-cli/tree/master/src/son/validate#api)

**Comment by lconceicao** [comment]
@jbonnet son-validate doesn't support this feature yet. I will have to sync with @dang03 on this, but it should be simple.

**Comment by lconceicao** [comment]
@jbonnet I have some questions/comments related to this.
From what I understood from talking with @dang03 (please correct me if I'm wrong) is that the GK will need to provide the validator the following parameters:
- signature
- user's public key
- hash of the package or the package itself

So my question is: will the GK perform two distinct API calls, one for validating the package contents and other to validate the package signature, or just one call to validate all?
For the first option, son-validate will just have a new API address for signature validation and the package hash will have to be provided. In the second option son-validate API of package validation must be modified to support the new functionality.

**Comment by jbonnet** [comment]
@lconceicao Since:

1. package signing is optional (right, @dang03?)
1. the GK will have to pass `son-validator` the package for validation

I think the best option would be the second one you mention, with the current API being changed and extra (optional) parameter(s) being passed... what do you think?

**Comment by lconceicao** [comment]
Agreed. GK will not be responsible to generate the hash, just passes the package itself, leaving all the validation logic on the son-validate side. I will start working on this asap.

**Comment by jbonnet** [comment]
Package signing is done by the Validator
