### ISSUE TITLE
Make WIM data available

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#620]
To the BSS

**Comment by felipevicens** [comment]
@jbonnet VIM and WIM are in the same microservice: https://github.com/sonata-nfv/son-gkeeper/blob/master/son-gtkvim/routes/request.rb Should we split it? Should we rename this microservice as gtkia (Gatekeeper Infrastructure Abtraction)? 

WIM is available from GUI so it should be easy have it in the BSS.
https://github.com/sonata-nfv/son-gkeeper/blob/master/son-gtkapi/routes/wim.rb

The API returns the following:
{"uuid":"1234-12345678-12345678-1234","name":"AthensWan","attached_vims":["1111-22222222-33333333-4444"]}

**Comment by felipevicens** [comment]
@jbonnet Once we have the new table created in the IA, it will be accesible by this API.

**Comment by jbonnet** [comment]
@felipevicens So we can close this issue, right?

**Comment by felipevicens** [comment]
Yes! the API is accessible through gkapi.
