### ISSUE TITLE
get_metrics changes have broken the int-gtkkpi-prometheus integration test 

### ISSUE THREAD

**Issue by srodriguezOPT** [sonata-nfv/son-gkeeper#622]
int-gtkkpi-prometheus Integration test check the KPI creation/update using the first version of the get_metrics method:
* get all metrics: GET http://server:port/api/v2/kpis 
* get metric by bame: GET http://server:port/api/v2/kpis?name=metric_name
* get metric by name and labels: 
http://server:port/api/v2/kpis?name=metric_name&instance=instance_name&job=job_name&base_labels[label1]=value1&base_labels[label2]=value2

Is the GET /api/v2/kpis implementation closed? In that case we need to adapt the integration test

**Comment by jbonnet** [comment]
@srodriguezOPT 
Accidentally 👎 , I've 'destroyed' these endpoints... I'm fixing this now.

**Comment by jbonnet** [comment]
Hi, @mzacharioudakis 
I've created this bug while implementing the API for showing the collected kpis on the GUI... do you mind if that API changes slightly?
The current one is
`.../api/v2/kpis?name=...&start=...&end=...&step=...`
My proposal would be to add something like `collected`, like in
`.../api/v2/kpis/collected?name=...&start=...&end=...&step=...`

What do you think?

**Comment by mzacharioudakis** [comment]
Hi @jbonnet ,
No, I do not mind about this change! When you are ready, please let me know in order to make the changes in the GUI.

**Comment by jbonnet** [comment]
Testing the correcting PR for the endpoint
`.../api/v2/kpis/collected?name=...&start=...&end=...&step=...`

**Comment by jbonnet** [comment]
@srodriguezOPT please re-test: this was corrected by the PR #623
