### ISSUE TITLE
Change KPIs counters into gauges

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#630]
Changes #595

**Comment by jbonnet** [comment]
@pkarkazis 
Actually, it's more complex that I've first explained, sorry...
I'm using **counters**, which I think is correct because Ia want to **count requests** (package on-boarding, user registrations, etc.), but I'm including the **elapsed time** since the beginning of that process as a **label**... confusing? Yes!

So... shall I keep the **counters** but create another KPI only for the **elapsed time**?

CC: @srodriguezOPT, @mzacharioudakis, @trakadasp

**Comment by srodriguezOPT** [comment]
Hi,

take a look at https://github.com/sonata-nfv/son-gkeeper/blob/master/son-gtkkpi/README.md

**Comment by jbonnet** [comment]
Thanks, @srodriguezOPT, I just did, and found out I was wrong...
My conclusion is I don't need to change `counter`s into `gauge`s, since the number of requests never go down. What may go up or down is the time it takes to on-board a package... and this information is in the labels.

So, @mzacharioudakis, can you easily extract the time it took to on-board a package (or create a user) from the labels and create a nice graphic with it?

Thanks

**Comment by pkarkazis** [comment]
Hello  @jbonnet and @srodriguezOPT,
we can extract the "elapsed_time" without any problems. But, we have a minor issue regarding the kpi post. Now, we include the "elapsed time" and the "uuid" as labels the post to the monitoring system, this action creates a new record for each post in our time series DB (because these labels have unique values for each post). This approach is functional for now but it will cause scalability issues in the future. I suggest removing the UUID from the labels and define some time performance levels (ex. elapsed_times 10ms, 50ms 100ms etc). So, all packages with elapsed time less than 10ms will be posted with label: "elapsed_time=10" and so on. What's your opinion on this?

**Comment by jbonnet** [comment]
@pkarkazis 
Hm...
I thought this kind of 'processing' (to count how many packages were on-boarded in less than 10ms, between 10ms and 20ms, etc.) was to be made afterwards, and you preferred to have 'raw' data (every package's on-boarding time). Having this raw data is preferable (IMHO), since we can not guess all the KPIs the SP owner will want: if a new KPI is needed, raw data is there, and the KPI can be calculated for the past as well as for the future.
But I can do what's the simplest. Following your suggestion, we'd have to predefine those 'buckets' (0ms-10ms, 10ms-20ms,...), right?

**Comment by pkarkazis** [comment]
@jbonnet 
Yes, we have to predefine these 'buckets' or to create them at runtime. In any case, my concern has to do only with scalability, If you think that it is more important to keep raw data we can do it.

**Comment by jbonnet** [comment]
Right, @pkarkazis 
If it is not too costly for you, I'd like to keep the 'buckets' definition for later: main reason is 'what buckets do we need'? We can refine this later, either by dynamically (at run-time) creating the buckets or providing already calculated values in buckets.

What do you think?

**Comment by pkarkazis** [comment]
@jbonnet 
No problem, we can leave this for later. 
From our side, we are going to proceed with the current approach.

**Comment by jbonnet** [comment]
This change does not make sense: counting requests are still always adding up (increasing). The time the process took can be bigger or smaller than previous ones, but this representation is still not a gauge.
