### ISSUE TITLE
OPTIONS in /api/v2/records/services

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-gkeeper#633]
Hello @jbonnet, I think we need to implement OPTIONS in the gkapi for the route /api/v2/records/services because the BSS can't show the network services instances.

**Comment by srodriguezOPT** [comment]
Hi @jbonnet , @felipevicens:

OPTIONS http://sp.int3.sonata-nfv.eu:32001/api/v2/records works fine. Response 200:

> Access-Control-Allow-Headers →Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
> Access-Control-Allow-Methods →POST,PUT
> Access-Control-Allow-Origin →*
> Content-Length →0
> Content-Type →text/html;charset=utf-8
> X-Content-Type-Options →nosniff
> X-Frame-Options →SAMEORIGIN
> X-XSS-Protection →1; mode=block

but 

OPTIONS http://sp.int3.sonata-nfv.eu:32001/api/v2/records/services fails. Response 404:

> Content-Length →73
> Content-Type →application/json
> X-Cascade →pass
> X-Content-Type-Options →nosniff

**Comment by jbonnet** [comment]
Please retest, solved by PR #634

**Comment by felipevicens** [comment]
It is working 🆗
