### ISSUE TITLE
Make Location info available in VIM

### ISSUE THREAD

**Issue by srodriguezOPT** [sonata-nfv/son-gkeeper#637]
It's needed to make available the location info in the "GET vims" requests that allows the BSS to show the list of available locations where to configure the network services.

Related to https://github.com/sonata-nfv/son-bss/issues/82

**Comment by jbonnet** [comment]
@srodriguezOPT, @DarioValocchi 
Is this a VIM-related issue (the list of locations) or more a WIM-related one?

CC: @felipevicens

**Comment by srodriguezOPT** [comment]
Hi @jbonnet, @DarioValocchi 

I'm retrieving all the vim requests from GK with $http.get(ENV.apiEndpoint+"/vims"). 
With these requests BSS can obtain the location info: 
$http.get(ENV.apiEndpoint+"/vims/"+vimRequest)

obtaining something like 
{"vim_uuid":"1111-22222222-33333333-4441","vim_city":"Athens","vim_name":"Athens-200","vim_endpoint":"10.100.32.200","memory_used":12288,"memory_total":51200,"core_used":6,"core_total":20}

"vim_city" will be our location field and no new development will be required in the gatekeeper

**Comment by jbonnet** [comment]
Oh, great, @srodriguezOPT !
Can yu close the issue?

**Comment by DarioValocchi** [comment]
Hi @srodriguezOPT ,
that is exactly the field we're supossed to use for this purpose.
