### ISSUE TITLE
Add owner username to package on-boarding request

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#652]
This is a two-step feature:
1. convert access token to `username` (in the GK API);
1. include `username` in the upload request:
    * check first how's the request meta-data is currently being treated in the `son-gtkpkg` micro-service;

Use `POST` to an endpoint like `....'/network-services?username=<username>`

**Comment by jbonnet** [comment]
hey, @dang03 
To simplify our lives, I was thinking of giving the service that is part of the package and all its functions the same user (owner). But there's one detail I forgot: what about a function that is from some other user and is now being reused (by another user) in another service? Any thoughts on this?

**Comment by jbonnet** [comment]
Hello, @dang03 
Any ideas on the comment above?
Also: can the GK POST both the NSD **and** the `username` (as in `...'/network-services?username=<username>`, above), in the same call to the Catalogues?

**Comment by dang03** [comment]
Hi @jbonnet 
Thinking about your first comment, the `username` meta-data can be added to all descriptors of the package or simply just to the package file. In case a function form another user is being reused in another service, it is an important detail to think about, but I guess it won't have any impact, as the `username` is only stored as meta-data in the Catalogue side.

About the second comment, each descriptor API accepts the `username` with the same POST call:
`POST` `/network-services?username=<username>`
`POST` `/vnfs?username=<username>` 
`POST` `/packages?username=<username>`
`POST` `/son-packages?username=<username>`

**Comment by jbonnet** [comment]
Hey, @dang03 
PR #668 implements this, but I'm not yet closing the issue, since I couldn't get the `username` set to the one I passed. I mean, I create a new package, retrieve it, and the user still comes with `nill`...
We'll have to check this on monday...

**Comment by dang03** [comment]
Hi @jbonnet,
I found the issue:
- The GK API sends `username` info for descriptors but not for the package file. If you look at the descriptors in the catalogue, they have the `username` saved. However the son-package (file) does not have it.
The next call needs to add `?username='username'` as the other API calls.
`POST /catalogues/api/v2/son-packages`

**Comment by jbonnet** [comment]
Closed by PR #682
