### ISSUE TITLE
Fix update user public key null

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#675]
See #605

**Comment by jbonnet** [comment]
@dang03 
The UM is returning `200` with and empty body... is this correct?

**Comment by dang03** [comment]
@jbonnet,
Yes, it just returns HTTP code `200`

**Comment by jbonnet** [comment]
Ok, @dang03, can you retest, please?
PR #676 should have fixed this...

p.s.: `204` (No Content) would be better, no?

**Comment by dang03** [comment]
I'll apply that change (`204`)
Testing...

**Comment by dang03** [comment]
@jbonnet,
It now works perfectly!
I'll change the response code to `204` with the next PR

**Comment by jbonnet** [comment]
@dang03 :-)
Great! But that change will break the API code (I know, it shouldn't... :-( )
When do you plan to change that?

**Comment by dang03** [comment]
@jbonnet 
No problem, I have changed the API code to `204` too in `models/user.rb` , so you don't need to change it again.
I'll update it during this week.

**Comment by jbonnet** [comment]
You’re the top, @dang03, thanks!
