### ISSUE TITLE
GK Function API fails

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#678]
hi @jbonnet
The GK Function API is currently failing when:
`GET /api/v2/functions/:uuid`

With an authorized user, it returns:
```
{
  "error": {
    "code": 500,
    "message": "#<NoMethodError: undefined method `each' for #<String:0x00563ccb4c1248>>"
  }
}
```
This causes integration tests `int-1-gtkpkg-sp-catalogue` to fail

**Comment by jbonnet** [comment]
Thanks, @dang03, I'm working on it.

**Comment by jbonnet** [comment]
@dang03, PR #680 solved this, `int-1-gtkpkg-sp-catalogue`is **green** again.
Thanks,
