### ISSUE TITLE
GK Package API fails

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#693]
hi @jbonnet
The GK Package API is currently failing when `POST`ing a package:
`POST /api/v2/packages/?`

This causes integration tests  int-1-gtkpkg-sp-catalogue  to fail.
Trace info here:

`E, [2017-06-07T07:05:50.691701 #7] ERROR -- GtkApi::POST /api/v2/packages/?: Error during processing: There was a problem POSTing a package file to the Package validator
E, [2017-06-07T07:05:50.691793 #7] ERROR -- GtkApi::POST /api/v2/packages/?: Backtrace:
	/app/models/validator.rb:70:in rescue in valid_package?'
	/app/models/validator.rb:54:in valid_package?'
	/app/routes/package.rb:64:in block (2 levels) in <class:GtkApi>'
	/usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in call'`
`E, [2017-06-07T07:05:50.691833 #7] ERROR -- GtkApi::POST /api/v2/packages/?: Proceed without package being validated...`
`E, [2017-06-07 07:05:52#7] ERROR -- GtkApi::POST /api/v2/packages/?: leaving with {"error":{"code":500,"message":"Unknown status: 500 for package {\"package\"=>{:filename=>\"sonata-demo.son\", :type=>\"application/octet-stream\", :name=>\"package\", :tempfile=>#<Tempfile:/tmp/RackMultipart20170607-7-1pzvmld.son (closed)>, :head=>\"Content-Disposition: form-data; name=\\\"package\\\"; filename=\\\"sonata-demo.son\\\"\\r\\nContent-Type: application/octet-stream\\r\\n\"}}"}}`

**Comment by jbonnet** [comment]
Closed by PR #701
