### ISSUE TITLE
Integrate the Licence Manager

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#733]
See the design [here](https://github.com/sonata-nfv/son-gkeeper/wiki/Integrate-licence-management).

**Comment by jbonnet** [comment]
Hi, @srodriguezOPT 
While [designing this](https://github.com/sonata-nfv/son-gkeeper/wiki/Integrate-licence-management), a doubt came to my mind: are you expecting to have in the Licence Store **just licences of the private services** or also the **public services**?

Thanks,

**Comment by srodriguezOPT** [comment]
Hi @jbonnet ,

I'm expecting both public and private licences. Later the BSS will show a field that informs the user if the license is private or not.

**Comment by jbonnet** [comment]
Ok, @srodriguezOPT 
So, every time the GK receives a package, it opens it, checks type of licence of the service (and also functions?) and `POST`s to the Licence Store? Or shall we assume the developer does this off-line, and we just need to verify if there's a licence whenever a service is to be instantiated, a package downloaded, etc.?

**Doubt:** just services or also functions?

**Comment by srodriguezOPT** [comment]
Hi, @jbonnet 

It's more related with the off-line option:
1. based on the NSDs, the BSS builds the list of public/non-public licences that can be acquired.
2. when the user requests a licence, the BSS sends the request to the GK that stores the info.
3. the BSS can now retrieve the already acquired licences info from the GK

So, every time the GK receives a package, it stores the service and functions in the catalogue as until now. The GK only needs to verify if there's a licence whenever a service is to be instantiated or a package downloaded.

Just services (the BSS only works at service level)

**Comment by srodriguezOPT** [comment]
Hi, @jbonnet 

It's more related to the off-line option:
1. based on the NSDs, the BSS builds the list of public/non-public licences that can be acquired.
2. when the user requests a licence, the BSS sends the request to the GK that stores the info.
3. the BSS can now retrieve the already acquired licences info from the GK

So, every time the GK receives a package, it stores the service and functions in the catalogue as until now. The GK only needs to verify if there's a licence whenever a service is to be instantiated or a package downloaded.

Just services (the BSS only works at service level)

**Comment by jbonnet** [comment]
Hmm...
We've got something here...
It is the Licence Store who's supposed to store the licence (imagine Apple's AppStore here, or SRodrigues Store). The Store URL should be given by the developer in the NSD. The GK should call this URL to check if there's a licence...

The idea was to have the store completely independent of SONATA. We're implementing a store ourselves just to prove the concept.

How can I help you with this? I know this has not been very well defined...

**Comment by jbonnet** [comment]
Closed (for now...) with PR #748
