### ISSUE TITLE
Add time stamps to all KPIs

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#755]
As it has been done with the **on-boarded packages** KPI

**Comment by jbonnet** [comment]
Hi, @pkarkazis, @mzacharioudakis (cc @trakadasp)
While looking at what I'd done in this respect (on-boarded packages KPI), I found out there's a little misunderstanding about what I think would be better and useful ... What I think is needed,
 is something like what's in [this file (Histograms.xlsx)](https://github.com/sonata-nfv/son-gkeeper/files/1152219/Histograms.xlsx): 

* column G has example/dummy values (the times currently put into Prometheus);
* column H counts how many of those values are between 0 and 0.1, between 0.1 and 0.2, etc.

So, we would get a graph with those columns, stating how many packages were on-boarded in less than 0.1 sec, how many took between 0.1 sec and 0.2 sec, etc.

And for this, we wouldn't need the exact time, would we?

**Comment by jbonnet** [comment]
Hi, @pkarkazis, @mzacharioudakis (cc @trakadasp )
Do you agree with this suggestion?

**Comment by pkarkazis** [comment]
Hello, @jbonnet 
I agree with you regarding the "histogram" approach. The time periods (0-0.1, 0.1-0.2 secs etc ) are going to be predefined?

**Comment by jbonnet** [comment]
@pkarkazis 
They can be fixed for a start, but the best solution would be to adapt to incoming data, at least from time to time...

**Comment by jbonnet** [comment]
@pkarkazis, are these KPI timestamps ok?

Closed
