### ISSUE TITLE
Get/update userinfo 

### ISSUE THREAD

**Issue by pkarkazis** [sonata-nfv/son-gkeeper#760]
Hi @jbonnet,
I tried to retrieve user information  (https://sp.int3.sonata-nfv.eu/api/v2/userinfo ) and got the following error:

Response:
{
    "error": {
        "code": 404,
        "message": "/api/v2/userinfo not supported"
    }
}

also, we need a PUT method for the same api in order to be able make changes on user information (ex change email address etc)

**Comment by jbonnet** [comment]
Hi, @pkarkazis 
The endpoint is `GET .../api/v2/users`, but currently is returning the list of users registered. If you agree, I'll keep that for `admin` users, but return just the info belonging to the user that owns the authorization token for `developer` or `customer` kinds of users.

Is that ok?

**Comment by pkarkazis** [comment]
@jbonnet 
If we want to provide an user info update mechanism through gui (change contact email, password etc) we must send these fields.

**Comment by jbonnet** [comment]
Closed by PR #771

**Comment by jbonnet** [comment]
Hey, @pkarkazis, @mzacharioudakis 
Please test both GET and PUT. Thanks

Closed by PR #772
