### ISSUE TITLE
Fix favicon.ico

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#789]
`E, [2017-07-26 10:13:50#8] ERROR -- : {"error":{"code":404,"message":"/favicon.ico not supported"}}`

**Comment by jbonnet** [comment]
Hi, @mzacharioudakis, @srodriguezOPT 
The Gatekeeper API keeps receiving requests for this `/favicon.ico`, whish obviousy it does not support. Is there a wrong URL somewhere in the GUI or BSS that's causing it?

**Comment by srodriguezOPT** [comment]
Hi @jbonnet , @mzacharioudakis 

Yes, a favicon was missing in the BSS. With https://github.com/sonata-nfv/son-bss/pull/93, a sonata favicon is shown in the web browser tab.

![image](https://user-images.githubusercontent.com/15909508/29412837-9ad3ea08-835a-11e7-826e-aac56a61eb2e.png)

I think that this should solve the favicon request from the BSS side. Can you confirm it?

Thank you

**Comment by jbonnet** [comment]
+1, @srodriguezOPT
