### ISSUE TITLE
Fix empty user creation date

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#837]
Hey, @dang03 
When the user is created, the returned data is
```
{
    "created_at": null, 
    "email": "myself@example.com", 
    "secret": "bXlzZWxmOjEyMzQ=", 
    "user_type": "developer", 
    "username": "myself", 
    "uuid": "cb2790f8-bdd5-4293-8a77-bc570714f535"
}
```
Why is the `created_at` at `null`?!?

If a `GET` is done right after, everything looks great:
```
{
    "created_at": "2017-08-25T14:28:31+00:00", 
    "email": "myself@example.com", 
    "user_type": "developer", 
    "username": "myself", 
    "uuid": "cb2790f8-bdd5-4293-8a77-bc570714f535"
}
```

**Comment by dang03** [comment]
Hi @jbonnet 
That's a good find, didn't notice of this bug. I'm going to investigate it, seems a problem related to the MongoDB. I'll update this issue.

**Comment by dang03** [comment]
Hi @jbonnet 
The UM did not return the creation date when registering a new user. Now this is fixed, as the example shows, this is the response from the UM:
```
{
    "username": "user0880",
    "userId": "fc96a0ba-000f-4317-852f-e412f6e34cca",
    "created_at": "2017-08-31T06:51:37.465Z"
}
```
However, when registering a user through Gatekeeper API, keeps returning `"created_at": null`, so I'm working on the GK User API to fix it.

**Comment by jbonnet** [comment]
Great, @dang03,
Thanks!

**Comment by dang03** [comment]
Bug fixed. The user creation response from GK User API works fine:
```
{
    "username": "user06",
    "secret": "dXNlcjA2OjEyMzQ=",
    "uuid": "73618751-94d5-417b-8c92-1fb86d635464",
    "created_at": "2017-08-31T09:30:11.650Z",
    "user_type": "developer",
    "email": "user06.sonata@email.com"
}
```

**Comment by jbonnet** [comment]
Thank you, @dang03 !
