### ISSUE TITLE
POST /licences fails

### ISSUE THREAD

**Issue by srodriguezOPT** [sonata-nfv/son-gkeeper#859]
Hi @jbonnet 

$http.post(ENV.apiEndpoint+"/licences",data)

with var data={"service_uuid":id, "user_role":$localStorage.currentUser.user_role};

returns {"error":{"code":400,"message":"{}"}}

Ther "user_role" field is on the request data since the initial develop version and it is not needed but I think that it shouldn't fail because of it, right?

**Comment by jbonnet** [comment]
Hi, @srodriguezOPT 
I think PR #877 (and others before) fixes this... can you please confirm?

p.s.: thanks, @felipevicens !

**Comment by srodriguezOPT** [comment]
Hi @jbonnet,

The GK is sending the private service with no user_licence field so BSS thinks that is public.

**Comment by jbonnet** [comment]
Ok, @srodriguezOPT 
I'll close this issue and open a new one to support fixing that problem.
