### ISSUE TITLE
Fetch the user email on a service instantiation request

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#891]
And pass it to the SLM, for configuring the Monitoring.

**Comment by dang03** [comment]
There are some options to implement this:
- The access token provided in the instantiation request made by the customer already includes the `email`, however it is encoded. The GK could simply decode the token using UM public key, or GK could forward the access token to be decoded to UM `/api/v1/userinfo` and receive the following response, which includes the `email`, e.g.:
```
 {"sub":"8031545e-d4da-4086-8cb2-a417f3460de2","name":"myName myLastName","preferred_username":"tester01","given_name":"myName","family_name":"myLastName","email":"myname.company@email.com"} 
```
- The GK can request to the UM ` /api/v1/users?username=` the user's information and parse the `email`

**Comment by jbonnet** [comment]
...and also the phone, and sent it to the SLM:
```
...
	user_data:
		email: joe@example.com
		phone: 00351966045047
...
```

**Comment by jbonnet** [comment]
Bon dia, @dang03 
We'll also need the `phone` when available, and it seems to me that the above `{"sub":"8031545e-d4da...` does not contain it... can you please add to it? Or suggest another API to be used?

Thanks

**Comment by dang03** [comment]
Boa tarde @jbonnet,
 This `/api/v1/userinfo` just returns some limited fields, so in order to get the `phone_number`, then you need to use ` /api/v1/users?username=` as endpoint, which includes the `attributes` hash with additional user information. When requesting the `/users` API, you can expect this response:
```
[
    {
        "id": "3cff0e19-4e65-415e-ad63-56cf6e2d763a",
        "createdTimestamp": 1507638054312,
        "username": "test01",
        "enabled": true,
        "totp": false,
        "emailVerified": false,
        "firstName": "test",
        "lastName": "sonata",
        "email": "test01@sonata.net",
        "attributes": {
            "phone_number": [
                "123456"
            ],
            "userType": [
                "developer"
            ],
            "certificate": null,
            "instances_private_key": null,
            "instances_public_key": null,
            "public_key": null
        },
...
```
You need to parse `attributes` hash, get `phone_number` value (if available), which is an array, not a string (Keycloak format).

**Comment by jbonnet** [comment]
Thanks, @dang03, just used it.
@tsoenen & @pkarkazis: customer's email is being passed in the request to the MANO as shown below:
![screen shot 2017-10-10 at 14 23 22](https://user-images.githubusercontent.com/11843/31388703-c30de564-adc6-11e7-845b-2e0f0b387e35.png)

I've already included the placeholder for the developer's data, in case we decide to implement it, so the format is a bit different from what we had agreed (just let me know if this brings you trouble)

**Comment by tsoenen** [comment]
Looks good.

Do we need a flag that indicates whether the developer is allowed to get monitoring data? Or is this reflected by the developers email field being empty?

**Comment by jbonnet** [comment]
Yes, @tsoenen, emptyness should indicate non-existence... Or the GK may not even include the empty fields, whatever you and @pkarkazis prefer, like in:
```
user_data:
  customer:
    email: sonata.admin@email.com
```
What do you think?

**Comment by tsoenen** [comment]
@pkarkazis : will these fields be optional or mandatory in the payload for the Monitoring Manager?

**Comment by pkarkazis** [comment]
Hi, @jbonnet @tsoenen :  I think that the best practice is to include fields for both customer and developer in the message to the monitoring manager and in case which notifications must be generated only for customer, developer's email address could be null or empty.
