### ISSUE TITLE
Retrieved package files not woking

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#941]
When downloading SONATA package files (.son) from GK API `/packages/uuid/download`, retrieved file can't be opened. It seems that content's bytes are missing or extra added.

If the same operation is done through Catalogue API `/son-packages/uuid`, the retrieved file can be opened. Let's check which part of the process modifies the package file.

**Comment by jbonnet** [comment]
hey, @dang03 
Sorry, I hadn't seen this bug before.. maybe it's a 'file type' kind of bug? I'll have a look into it...

**Comment by dang03** [comment]
Hi @jbonnet,
I have addressed this issue and retrieved package files are fine now.

**Comment by jbonnet** [comment]
:-)
Thank you, @dang03 !
